### ISSUE TITLE
import from word is broken copy/paste

### ISSUE THREAD

**Issue by burnedsyn** [xchwarze/ckeditor-phpbb#1]
i have been called by a customer to resolve this issue for him as no new line or new paragraphe where interpreted.
I have solved this issues for him but you need to config this in your plugin.
so 

in the  file : 

This line
 'forcePasteAsText'      => (bool)$this->config['dsr_cke_force_paste_as_text'],
 
this can hold other value than bool ! 
and one of them is 'allow-word' which resolve this issue
So i think you have to reflect this in your setup and config
Have a nice day

**Comment by xchwarze** [comment]
I understand that the functionality you say was never merged
https://github.com/ckeditor/ckeditor4/issues/3269

Or at least that's what several comments on various ckeditor threads say.

**Comment by xchwarze** [comment]
Fixed in master version
